import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations._();

  static const supportedLocales = [Locale('sq'), Locale('en')];

  static String t(BuildContext context, String key) {
    final code = Localizations.localeOf(context).languageCode;
    final table = _localized[code] ?? _localized['en']!;
    return table[key] ?? key;
  }

  static const Map<String, Map<String, String>> _localized = {
    'sq': {
      'admin': 'Admin',
      'switchToLight': 'Kalo ne light mode',
      'switchToDark': 'Kalo ne dark mode',
      'language': 'Gjuha',
      'langSq': 'Shqip',
      'langEn': 'Anglisht',
      'backToPublic': 'Kthehu ne app publik',
      'signOut': 'Dil',
      'dashboard': 'Paneli',
      'athletes': 'Sportistet',
      'news': 'Lajmet',
      'events': 'Eventet',
      'matches': 'Ndeshjet',
      'gallery': 'Galeria',
      'sponsors': 'Sponsorat',
      'ads': 'Reklamat',
      'autopost': 'Autopost',
      'training': 'Stervitja',
      'chat': 'Chat',
      'home': 'Kreu',
      'team': 'Ekipi',
      'results': 'Rezultatet',
      'live': 'Live',
      'aboutClub': 'Rreth klubit',
      'trainingSchedule': 'Orari i stervitjes',
      'noTrainingYet': 'Ende s’ka seanca stervitjeje',
      'trainingEmptySubtitle': 'Admini mund te publikoj planin javor ketu.',
      'clubChat': 'Chat i klubit',
      'membership': 'Anetaresim',
      'appSubtitle': 'Wresling Club',
      'latestNews': 'Lajmet e fundit',
      'upcomingEvents': 'Eventet e ardhshme',
      'adsPlaceholder': 'Reklama (placeholder)',
      'noEventsYet': 'Ende s’ka evente',
      'eventsEmptySubtitle': 'Shto evente dhe turne nga paneli admin.',
      'noGalleryYet': 'Ende s’ka elemente ne galeri',
      'galleryEmptySubtitle': 'Admini do te ngarkoje foto dhe video.',
      'noResultsYet': 'Ende s’ka rezultate',
      'resultsEmptySubtitle':
          'Rezultatet do te shfaqen pasi t’i shtoje admini.',
      'noAthletesYet': 'Ende s’ka sportiste',
      'teamEmptySubtitle': 'Admini do te shtoje sportistet ne ekip.',
      'noSponsorsYet': 'Ende s’ka sponsora',
      'sponsorsEmptySubtitle': 'Bannerat e sponsoreve do te shfaqen ketu.',
      'noAdsYet': 'Ende s’ka reklama',
      'adsEmptySubtitle': 'Reklamat mund te konfigurohen nga admini.',
      'liveStreaming': 'Transmetim Live',
      'liveNotConfigured': 'Transmetimi live nuk eshte konfiguruar',
      'livePlaceholderSubtitle':
          'Placeholder per YouTube Live / Facebook Live embeds.\n\n'
          'Admin/zhvillues: ruaj URL-te e stream ne Firestore dhe nderto player-in ketu.',
      'membershipPlaceholder': 'Placeholder anetaresimi',
      'membershipPlaceholderSubtitle':
          'Skeleton monetizimi:\n'
          '- paketa anetaresimi\n'
          '- permbajtje premium\n'
          '- donacione\n\n'
          'Admin/zhvillues: lidh pagesat dhe mbro permbajtjen me role.',
      'aboutTitle': 'Rreth klubit',
      'whoWeAre': 'Kush jemi',
      'whoWeAreBody':
          'Kolosi Infinit Wrestling Club fokusohet ne zhvillimin e te rinjve, '
          'disiplinen dhe performancen e larte ne mundje. Klubi mbeshtet '
          'fillestare, sportiste garues dhe te rritur qe duan stervitje te '
          'strukturuar ne ambient te sigurt.',
      'whatWeOffer': 'Cfare ofrojme',
      'whatWeOfferBody':
          '- Klasa teknike per te gjitha nivelet\n'
          '- Pergatitje fizike dhe force\n'
          '- Pergatitje per gara dhe coachim\n'
          '- Evente ekipore dhe aktivitete te klubit',
      'clubValues': 'Vlerat e klubit',
      'clubValuesBody':
          'Respekt. Disipline. Fryme ekipore. Progres i vazhdueshem.',
      'contact': 'Kontakt',
      'chatNoMessages': 'Ende s’ka mesazhe',
      'chatNoMessagesSubtitle': 'Njoftimet e adminit do te shfaqen ketu.',
      'fullNamePromptTitle': 'Shkruaj emrin e plote',
      'fullName': 'Emri i plote',
      'fullNameHint': 'p.sh. Arlind Krasniqi',
      'later': 'Me vone',
      'save': 'Ruaj',
      'iWillParticipate': 'Marr pjese',
      'iWillNotParticipate': 'Nuk marr pjese',
      'meWillParticipate': 'Une: Marr pjese',
      'meWillNotParticipate': 'Une: Nuk marr pjese',
      'published': 'Publikuar',
      'starts': 'Fillon',
      'adminLogin': 'Hyrja Admin',
      'publicApp': 'App publik',
      'signIn': 'Hyr',
      'email': 'Email',
      'password': 'Fjalekalimi',
      'signingIn': 'Duke hyr...',
      'adminLoginNote':
          'Shenim: Ky eshte panel vetem per admin. Krijo user admin ne Firebase Auth, pastaj shto UID ne Firestore te admins/{uid}.',
      'adminDashboard': 'Paneli i adminit',
      'adminDashboardTip':
          'Gjithcka nis bosh. Perdori keto seksione per te mbushur app-in e klubit.\n\n'
          'Keshille: ngarko media fillimisht (Galeria), pastaj perdor URL-te ne Lajme/Evente/Sponsora/Reklama.',
      'trainingLocation': 'Lokacioni',
      'trainingCoach': 'Trajneri',
      'chatAdmin': 'Admin',
      'noTitle': '(Pa titull)',
      'add': 'Shto',
      'addMessage': 'Shto mesazh',
      'edit': 'Ndrysho',
      'delete': 'Fshi',
      'cancel': 'Anulo',
      'pick': 'Zgjidh',
      'title': 'Titulli',
      'message': 'Mesazhi',
      'startsAt': 'Fillon ne',
      'notSet': 'I papershkruar',
      'adminBroadcastChat': 'Chat broadcast i adminit',
      'noAdminMessages': 'S’ka mesazhe admini',
      'noAdminMessagesSubtitle':
          'Krijo mesazhin e pare broadcast per anetaret.',
      'participationConfirmationActive': 'Konfirmim pjesemarrje: AKTIV',
      'responses': 'Pergjigje',
      'trainingSessionsAdmin': 'Seancat e stervitjes',
      'noTrainingSessionsAdmin': 'S’ka seanca stervitjeje',
      'trainingAdminSubtitle':
          'Shto hyrje javore te orarit per anetare dhe sportiste.',
      'noDetailsYet': 'Ende pa detaje',
      'addAnnouncement': 'Shto njoftim',
      'editAnnouncement': 'Ndrysho njoftimin',
      'announcementStartHelp': 'Fillimi i njoftimit / eventit',
      'requireParticipation': 'Kerko konfirmim pjesemarrjeje',
      'requireParticipationSubtitle':
          'Anetaret do te japin: Marr pjese / Nuk marr pjese.',
      'announcementEntityLabel': 'njoftimin',
      'trainingEntityLabel': 'stervitjen',
      'editAthlete': 'Ndrysho sportistin',
      'addAthlete': 'Shto sportist',
      'positionOptional': 'Pozicioni (opsionale)',
      'numberOptional': 'Numri (opsionale)',
      'photoUrlOptional': 'URL e fotos (opsionale)',
      'bioOptional': 'Biografia (opsionale)',
      'galleryUrlTip':
          'Keshille: ngarko ne Admin -> Galeria dhe vendos URL-ne.',
      'editNews': 'Ndrysho lajmin',
      'addNews': 'Shto lajm',
      'coverImageUrlOptional': 'URL e fotos se kopertines (opsionale)',
      'directImageUrlTip':
          'Vendos link direkt te fotos (.jpg/.png/.webp), jo link te faqes.',
      'directImageUrlError':
          'Jep nje URL direkte imazhi (p.sh. qe perfundon me .jpg ose .png).',
      'coverImageSource': 'Burimi i fotos se kopertines',
      'usePublicUrl': 'Perdor URL publike',
      'uploadPhoto': 'Ngarko foto',
      'pickPhoto': 'Zgjidh foto',
      'selectedPhoto': 'Foto e zgjedhur',
      'pickPhotoFirst': 'Zgjidh foton fillimisht.',
      'bodyOptional': 'Permbajtja (opsionale)',
      'keepBlankLater':
          'Mund ta lesh bosh tani; admini mund ta plotesoje me vone.',
      'editEvent': 'Ndrysho eventin',
      'addEvent': 'Shto event',
      'eventStartHelp': 'Fillimi i eventit',
      'eventEndHelp': 'Mbarimi i eventit',
      'start': 'Fillimi',
      'end': 'Mbarimi',
      'bannerUrlOptional': 'URL e bannerit (opsionale)',
      'bannerImageSource': 'Burimi i bannerit',
      'descriptionOptional': 'Pershkrimi (opsionale)',
      'editMatch': 'Ndrysho ndeshjen',
      'addMatch': 'Shto ndeshje',
      'opponent': 'Kundershtari',
      'competitionOptional': 'Kompeticioni (opsionale)',
      'homeMatch': 'Ndeshje ne shtepi',
      'matchDate': 'Data e ndeshjes',
      'homeScoreOptional': 'Golat tone (opsionale)',
      'awayScoreOptional': 'Golat e kundershtarit (opsionale)',
      'highlightsUrlOptional': 'URL e highlights (opsionale)',
      'highlightsHelper': 'Lidhje YouTube / Facebook video.',
      'editSponsor': 'Ndrysho sponsorin',
      'addSponsor': 'Shto sponsor',
      'name': 'Emri',
      'tierOptional': 'Kategoria (opsionale)',
      'tierExample': 'Shembull: Gold / Silver / Bronze',
      'logoUrlOptional': 'URL e logos (opsionale)',
      'logoImageSource': 'Burimi i logos',
      'websiteUrlOptional': 'URL e faqes (opsionale)',
      'editTrainingSession': 'Ndrysho seancen e stervitjes',
      'addTrainingSession': 'Shto seance stervitjeje',
      'trainingStartHelp': 'Fillimi i stervitjes',
      'trainingEndHelp': 'Mbarimi i stervitjes',
      'locationOptional': 'Lokacioni (opsionale)',
      'coachOptional': 'Trajneri (opsionale)',
      'editAd': 'Ndrysho reklamen',
      'addAd': 'Shto reklame',
      'placementOptional': 'Pozicioni (opsionale)',
      'placementExample': 'Shembull: home_top, sponsors_page, results_bottom',
      'active': 'Aktive',
      'imageUrlOptional': 'URL e imazhit (opsionale)',
      'clickUrlOptional': 'URL e klikimit (opsionale)',
      'startsAtHelp': 'Nis ne',
      'endsAtHelp': 'Perfundon ne',
      'ends': 'Perfundon',
      'scheduleAutopost': 'Planifiko autopost',
      'notSetSendImmediately': 'I papershkruar (dergo menjehere)',
      'scheduleAutopostHelp': 'Planifiko autopost-in',
      'contentType': 'Lloji i permbajtjes',
      'contentDocumentId': 'ID e dokumentit te permbajtjes',
      'contentDocHelper':
          'Vendos ID-ne e dokumentit Firestore qe do te postohet.',
      'platforms': 'Platformat',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'youtube': 'YouTube',
      'autopostPlatformsForThisMedia':
          'Autopost per kete media (zgjedh rrjetet)',
      'autopostNoPlatformMeansOff':
          'Nese nuk zgjedh asnje rrjet, kjo media nuk autopostohet.',
      'scheduled': 'I planifikuar',
      'createJob': 'Krijo pune',
      'newsItem': 'Lajm',
      'eventItem': 'Event',
      'galleryItem': 'Element galerie',
      'matchItem': 'Ndeshje',
      'placeholderQueueText':
          'Kjo eshte radhe placeholder.\nFirebase Functions do te procesoje punet dhe do te lidhet me API-te e platformave.',
      'uploadGalleryMedia': 'Ngarko media ne galeri',
      'pickFile': 'Zgjidh skedar',
      'picked': 'I zgjedhur',
      'thisFileIsVideo': 'Ky skedar eshte video',
      'videoThumbTodo': 'Thumbnail per video eshte TODO placeholder.',
      'captionOptional': 'Pershkrimi i shkurter (opsionale)',
      'uploadsInfoText':
          'Ngarkohet ne Firebase Storage, pastaj krijohet dokument ne Firestore `gallery`.\nZhvillues: shto gjenerim real thumbnails per video me Cloud Functions.',
      'upload': 'Ngarko',
      'uploading': 'Duke ngarkuar...',
      'editGalleryItem': 'Ndrysho elementin e galerise',
      'thumbnailUrlOptional': 'URL e thumbnail (opsionale)',
      'thumbnailHelper':
          'Per video, shto URL thumbnail (ose gjeneroje me Cloud Functions).',
      'galleryMetaTodo':
          'Zhvillues: ruaj metadata shtese ketu (tags, kategori, etj).',
    },
    'en': {
      'admin': 'Admin',
      'switchToLight': 'Switch to light mode',
      'switchToDark': 'Switch to dark mode',
      'language': 'Language',
      'langSq': 'Albanian',
      'langEn': 'English',
      'backToPublic': 'Back to public app',
      'signOut': 'Sign out',
      'dashboard': 'Dashboard',
      'athletes': 'Athletes',
      'news': 'News',
      'events': 'Events',
      'matches': 'Matches',
      'gallery': 'Gallery',
      'sponsors': 'Sponsors',
      'ads': 'Ads',
      'autopost': 'Autopost',
      'training': 'Training',
      'chat': 'Chat',
      'home': 'Home',
      'team': 'Team',
      'results': 'Results',
      'live': 'Live',
      'aboutClub': 'About Club',
      'trainingSchedule': 'Training Schedule',
      'noTrainingYet': 'No training sessions yet',
      'trainingEmptySubtitle':
          'Admin can publish the weekly training schedule here.',
      'clubChat': 'Club Chat',
      'membership': 'Membership',
      'appSubtitle': 'Wrestling Club',
      'latestNews': 'Latest News',
      'upcomingEvents': 'Upcoming Events',
      'adsPlaceholder': 'Ads (placeholder)',
      'noEventsYet': 'No events yet',
      'eventsEmptySubtitle': 'Add tournaments and events from the admin panel.',
      'noGalleryYet': 'No gallery items yet',
      'galleryEmptySubtitle': 'Admin will upload photos and videos.',
      'noResultsYet': 'No matches yet',
      'resultsEmptySubtitle': 'Results will appear here once added by admin.',
      'noAthletesYet': 'No athletes yet',
      'teamEmptySubtitle': 'Admin will add players to the roster.',
      'noSponsorsYet': 'No sponsors yet',
      'sponsorsEmptySubtitle': 'Sponsor banners will appear here.',
      'noAdsYet': 'No ads yet',
      'adsEmptySubtitle': 'Ads placeholders can be configured by admin.',
      'liveStreaming': 'Live Streaming',
      'liveNotConfigured': 'Live streaming not configured',
      'livePlaceholderSubtitle':
          'Placeholder for YouTube Live / Facebook Live embeds.\n\n'
          'Admin/developer: store stream URLs in Firestore and build an embed player here.',
      'membershipPlaceholder': 'Membership placeholder',
      'membershipPlaceholderSubtitle':
          'Monetization skeleton:\n'
          '- membership tiers\n'
          '- premium content\n'
          '- donations\n\n'
          'Admin/developer: connect payment provider and protect content with roles.',
      'aboutTitle': 'About The Club',
      'whoWeAre': 'Who we are',
      'whoWeAreBody':
          'Kolosi Infinit Wrestling Club is focused on youth development, '
          'discipline, and high-performance wrestling. The club supports '
          'beginners, competitive athletes, and adults who want structured '
          'training in a safe environment.',
      'whatWeOffer': 'What we offer',
      'whatWeOfferBody':
          '- Technique classes for all levels\n'
          '- Strength and conditioning support\n'
          '- Competition preparation and coaching\n'
          '- Team events and club activities',
      'clubValues': 'Club values',
      'clubValuesBody':
          'Respect. Discipline. Team spirit. Continuous progress.',
      'contact': 'Contact',
      'chatNoMessages': 'No messages yet',
      'chatNoMessagesSubtitle': 'Admin announcements will appear here.',
      'fullNamePromptTitle': 'Enter full name',
      'fullName': 'Full name',
      'fullNameHint': 'e.g. Arlind Krasniqi',
      'later': 'Later',
      'save': 'Save',
      'iWillParticipate': 'I will participate',
      'iWillNotParticipate': 'I will not participate',
      'meWillParticipate': 'Me: I will participate',
      'meWillNotParticipate': 'Me: I will not participate',
      'published': 'Published',
      'starts': 'Starts',
      'adminLogin': 'Admin Login',
      'publicApp': 'Public app',
      'signIn': 'Sign in',
      'email': 'Email',
      'password': 'Password',
      'signingIn': 'Signing in...',
      'adminLoginNote':
          'Note: This is an admin-only skeleton. Create an admin user in Firebase Auth, then allowlist the UID in Firestore at admins/{uid}.',
      'adminDashboard': 'Admin Dashboard',
      'adminDashboardTip':
          'Everything starts empty. Use these sections to populate the club app.\n\n'
          'Tip: Upload media first (Gallery), then reference URLs in News/Events/Sponsors/Ads.',
      'trainingLocation': 'Location',
      'trainingCoach': 'Coach',
      'chatAdmin': 'Admin',
      'noTitle': '(No title)',
      'add': 'Add',
      'addMessage': 'Add message',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'pick': 'Pick',
      'title': 'Title',
      'message': 'Message',
      'startsAt': 'Starts at',
      'notSet': 'Not set',
      'adminBroadcastChat': 'Admin Broadcast Chat',
      'noAdminMessages': 'No admin messages',
      'noAdminMessagesSubtitle':
          'Create your first broadcast message for members.',
      'participationConfirmationActive': 'Participation confirmation: ACTIVE',
      'responses': 'Responses',
      'trainingSessionsAdmin': 'Training Sessions',
      'noTrainingSessionsAdmin': 'No training sessions',
      'trainingAdminSubtitle':
          'Add weekly schedule entries for members and athletes.',
      'noDetailsYet': 'No details yet',
      'addAnnouncement': 'Add announcement',
      'editAnnouncement': 'Edit announcement',
      'announcementStartHelp': 'Announcement / event start',
      'requireParticipation': 'Require participation confirmation',
      'requireParticipationSubtitle':
          'Members will choose: I will participate / I will not participate.',
      'announcementEntityLabel': 'announcement',
      'trainingEntityLabel': 'training',
      'editAthlete': 'Edit athlete',
      'addAthlete': 'Add athlete',
      'positionOptional': 'Position (optional)',
      'numberOptional': 'Number (optional)',
      'photoUrlOptional': 'Photo URL (optional)',
      'bioOptional': 'Bio (optional)',
      'galleryUrlTip': 'Tip: upload in Admin -> Gallery and paste the URL.',
      'editNews': 'Edit news',
      'addNews': 'Add news',
      'coverImageUrlOptional': 'Cover image URL (optional)',
      'directImageUrlTip':
          'Use a direct image link (.jpg/.png/.webp), not a webpage URL.',
      'directImageUrlError':
          'Provide a direct image URL (for example ending in .jpg or .png).',
      'coverImageSource': 'Cover image source',
      'usePublicUrl': 'Use public URL',
      'uploadPhoto': 'Upload photo',
      'pickPhoto': 'Pick photo',
      'selectedPhoto': 'Selected photo',
      'pickPhotoFirst': 'Pick a photo first.',
      'bodyOptional': 'Body (optional)',
      'keepBlankLater': 'Keep blank for now; admin can fill later.',
      'editEvent': 'Edit event',
      'addEvent': 'Add event',
      'eventStartHelp': 'Event start',
      'eventEndHelp': 'Event end',
      'start': 'Start',
      'end': 'End',
      'bannerUrlOptional': 'Banner URL (optional)',
      'bannerImageSource': 'Banner source',
      'descriptionOptional': 'Description (optional)',
      'editMatch': 'Edit match',
      'addMatch': 'Add match',
      'opponent': 'Opponent',
      'competitionOptional': 'Competition (optional)',
      'homeMatch': 'Home match',
      'matchDate': 'Match date',
      'homeScoreOptional': 'Home score (optional)',
      'awayScoreOptional': 'Away score (optional)',
      'highlightsUrlOptional': 'Highlights URL (optional)',
      'highlightsHelper': 'YouTube / Facebook video link placeholder.',
      'editSponsor': 'Edit sponsor',
      'addSponsor': 'Add sponsor',
      'name': 'Name',
      'tierOptional': 'Tier (optional)',
      'tierExample': 'Example: Gold / Silver / Bronze',
      'logoUrlOptional': 'Logo URL (optional)',
      'logoImageSource': 'Logo source',
      'websiteUrlOptional': 'Website URL (optional)',
      'editTrainingSession': 'Edit training session',
      'addTrainingSession': 'Add training session',
      'trainingStartHelp': 'Training start',
      'trainingEndHelp': 'Training end',
      'locationOptional': 'Location (optional)',
      'coachOptional': 'Coach (optional)',
      'editAd': 'Edit ad',
      'addAd': 'Add ad',
      'placementOptional': 'Placement (optional)',
      'placementExample': 'Example: home_top, sponsors_page, results_bottom',
      'active': 'Active',
      'imageUrlOptional': 'Image URL (optional)',
      'clickUrlOptional': 'Click URL (optional)',
      'startsAtHelp': 'Starts at',
      'endsAtHelp': 'Ends at',
      'ends': 'Ends',
      'scheduleAutopost': 'Schedule autopost',
      'notSetSendImmediately': 'Not set (send immediately)',
      'scheduleAutopostHelp': 'Schedule autopost',
      'contentType': 'Content type',
      'contentDocumentId': 'Content document ID',
      'contentDocHelper': 'Paste the Firestore doc id you want to post.',
      'platforms': 'Platforms',
      'facebook': 'Facebook',
      'instagram': 'Instagram',
      'youtube': 'YouTube',
      'autopostPlatformsForThisMedia':
          'Autopost for this media (choose networks)',
      'autopostNoPlatformMeansOff':
          'If no network is selected, this media will not be autoposted.',
      'scheduled': 'Scheduled',
      'createJob': 'Create job',
      'newsItem': 'News',
      'eventItem': 'Event',
      'galleryItem': 'Gallery item',
      'matchItem': 'Match',
      'placeholderQueueText':
          'This is a placeholder queue.\nFirebase Functions will process jobs and call platform APIs.',
      'uploadGalleryMedia': 'Upload gallery media',
      'pickFile': 'Pick file',
      'picked': 'Picked',
      'thisFileIsVideo': 'This file is a video',
      'videoThumbTodo': 'Video thumbnails are a TODO placeholder.',
      'captionOptional': 'Caption (optional)',
      'uploadsInfoText':
          'Uploads to Firebase Storage, then creates a Firestore `gallery` doc.\nDeveloper: add real video thumbnail generation via Cloud Functions.',
      'upload': 'Upload',
      'uploading': 'Uploading...',
      'editGalleryItem': 'Edit gallery item',
      'thumbnailUrlOptional': 'Thumbnail URL (optional)',
      'thumbnailHelper':
          'For videos, add a thumbnail URL (or generate one via Cloud Functions).',
      'galleryMetaTodo':
          'Developer: store additional metadata here (tags, categories, etc).',
    },
  };
}
